export default {
    SET_ACCOUNTS: 'SET_ACCOUNTS',
    SET_MAIN_ACCOUNT: 'SET_MAIN_ACCOUNT',
    CHECK_MAIN_ACCOUNT: 'CHECK_MAIN_ACCOUNT',
    SET_ETH_BALANCE: 'SET_ETH_BALANCE',
    SET_BTC_BALANCE: 'SET_BTC_BALANCE',
    SET_DOT_BALANCE: 'SET_DOT_BALANCE',
    SET_EOS_BALANCE: 'SET_EOS_BALANCE'
}