export default {
  SET_ACCOUNTS: 'SET_ACCOUNTS',
  SET_MAIN_ACCOUNT: 'SET_MAIN_ACCOUNT',
  CHECK_MAIN_ACCOUNT: 'CHECK_MAIN_ACCOUNT',
  FETCH_BALANCES: 'FETCH_BALANCES',
  SET_BALANCE: 'SET_BALANCE',
  CHANGE_NAVIGATION: 'CHANGE_NAVIGATION',
  SET_BENEFICIAREIES: 'SET_BENEFICIAREIES',
  INIT: 'INIT'
};
